version: '3.8'
services:
  aspnet-pokeapi:
    build: .
    restart: unless-stopped
    depends_on:
      - mysql-server
    ports:
      - '8080:8080'
  mysql-server:
    image:  mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: pokemon
